services:
  - type: web
    name: slovolov-download
    runtime: static
    rootDir: web-app
    buildCommand: npm ci && npm run build
    staticPublishPath: dist
    pullRequestPreviewsEnabled: false
